update workflow

diff --git a/.github/workflows/validate-deployment.yaml b/.github/workflows/validate-deployment.yaml
--- a/.github/workflows/validate-deployment.yaml
+++ b/.github/workflows/validate-deployment.yaml
@@ -6,6 +6,7 @@ on:
 
 env:
   SERVICE_NAME: licensing-example-java
+  SERVICE_PLAN: licensing-example-java
   MAIN_RESOURCE_NAME: licensing-example-java
   ENVIRONMENT_TYPE: Dev
   CLOUD_PROVIDER: aws
@@ -26,25 +27,28 @@ jobs:
 
       - name: Create Instance
         id: create_instance
+        env:
+          ENVIRONMENT: ${{ env.ENVIRONMENT_TYPE }}
+          CLOUD_PROVIDER: ${{ env.CLOUD_PROVIDER }}
+          REGION: ${{ env.REGION }}
+          SERVICE_PLAN: ${{ env.SERVICE_PLAN }}
+          SERVICE_NAME: ${{ env.SERVICE_NAME }}
+          MAIN_RESOURCE_NAME: ${{ env.MAIN_RESOURCE_NAME }}
         run: |
           INSTANCE_ID=$(omnistrate-ctl instance create --environment ${ENVIRONMENT} --cloud-provider ${CLOUD_PROVIDER} --region ${REGION} --plan ${SERVICE_PLAN} --service ${SERVICE_NAME} --resource ${MAIN_RESOURCE_NAME} --output json | jq -r '.instance_id')
-          if EXIT_CODE=$?; [ $EXIT_CODE -ne 0 ]; then
-              echo "Failed to get instance status"
-              exit $EXIT_CODE
-          fi
           echo "instance_id=$INSTANCE_ID" >> $GITHUB_OUTPUT
 
       - name: Check Instance Status
         timeout-minutes: 10
         run: |
+              if [ -z "${{ steps.create_instance.outputs.instance_id }}" ]; then
+                echo "Failed to create instance"
+                exit 1
+              fi
               echo "Waiting for instance to become RUNNING..."
               STATUS="DEPLOYING"
               while [ "$STATUS" != "RUNNING" ]; do
               STATUS=$(omnistrate-ctl instance describe ${{ steps.create_instance.outputs.instance_id }} -o json | jq -r '.consumptionResourceInstanceResult.status')
-              if EXIT_CODE=$?; [ $EXIT_CODE -ne 0 ]; then
-                echo "Failed to get instance status"
-                exit $EXIT_CODE
-              fi
               echo "Instance Status: $STATUS"
               if [ "$STATUS" = "FAILED" ]; then
                 echo "Instance deployment failed"
